source 'https://rubygems.org'
ruby '3.2.3'

gem 'mastodon-api', '~> 1.1', require: 'mastodon'
gem 'dotenv'
gem 'json', '~> 2.7'
gem 'activesupport', require: 'active_support/all'
gem 'googleauth', '~> 1.9'
gem 'google-apis-sheets_v4', '~> 0.26'
gem 'faraday', '~> 2.7'
gem 'nokogiri', '~> 1.15'
